services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Macpaw\SchemaContextBundle\Service\BaggageSchemaResolver:
    arguments:
      $environmentSchema: '%schema_context.environment_schema%'
      $environmentName: '%schema_context.environment_name%'
      $schemaOverridableEnvironments: '%schema_context.overridable_environments%'
      $logger: '@Macpaw\SchemaContextBundle\Logger\DebugLogger'
    public: true
    shared: true

  Macpaw\SchemaContextBundle\Service\BaggageCodec:
    public: true
    shared: true

  Macpaw\SchemaContextBundle\EventListener\BaggageRequestListener:
    arguments:
      $baggageSchemaResolver: '@Macpaw\SchemaContextBundle\Service\BaggageSchemaResolver'
      $schemaRequestHeader: '%schema_context.header_name%'
      $logger: '@Macpaw\SchemaContextBundle\Logger\DebugLogger'
    tags:
      - { name: kernel.event_subscriber }

  Macpaw\SchemaContextBundle\Messenger\Middleware\BaggageSchemaMiddleware:
    arguments:
      $sendersLocator: '@messenger.senders_locator'
    tags:
      - { name: messenger.middleware }

  Macpaw\SchemaContextBundle\Logger\DebugLogger:
    arguments:
      $logger: null
