services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Macpaw\SchemaContextBundle\Service\BaggageSchemaResolver:
    public: true
    shared: true

  Macpaw\SchemaContextBundle\Service\BaggageCodec:
    public: true
    shared: true

  Macpaw\SchemaContextBundle\EventListener\BaggageRequestListener:
    arguments:
      $baggageSchemaResolver: '@Macpaw\SchemaContextBundle\Service\BaggageSchemaResolver'
      $schemaRequestHeader: '%schema_context.header_name%'
      $defaultSchema: '%schema_context.default_schema%'
      $appName: '%schema_context.app_name%'
      $allowedAppNames: '%schema_context.allowed_app_names%'
      $allowedAppNamesRegex: '%schema_context.allowed_app_names_regex%'
    tags:
      - { name: kernel.event_subscriber }

  Macpaw\SchemaContextBundle\Messenger\Middleware\BaggageSchemaMiddleware:
    tags:
      - { name: messenger.middleware }
